version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: DogExercise
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  web:
    build: .
    command:  gunicorn --bind :8000 DogExercise.wsgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
